---
- name: Create configuration directory for vim
  ansible.builtin.file:
    state: 'directory'
    dest: '/etc/vim'
    owner: 'root'
    group: 'root'
    mode: "0755"

- name: Configure global vimrc options
  ansible.builtin.template:
    src: 'vimrc.j2'
    dest: '{{ vim_path_vimrc }}'
    owner: 'root'
    group: 'root'
    mode: "0744"
