---
- name: Include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - '{{ ansible_system }}.yml'
    - 'default.yml'

- name: include install tasks
  ansible.builtin.import_tasks: "install.yml"

- name: include configure tasks
  ansible.builtin.import_tasks: "config.yml"
