---
- name: Include distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'
    - '{{ ansible_system }}.yml'
    - 'default.yml'

- name: Install vim
  ansible.builtin.package:
    name: "vim"
    state: present

- name: Create configuration directory for vim
  ansible.builtin.file:
    state: 'directory'
    dest: '/etc/vim'
    owner: 'root'
    group: 'root'
    mode: "0755"

- name: Configure global vimrc options
  ansible.builtin.template:
    src: 'vimrc.j2'
    dest: '{{ vim_path_vimrc }}'
    owner: 'root'
    group: 'root'
    mode: "0744"
