---
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current", "next"]
    platforms:
      - "debian9"
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "centos7"
      - "centos8"
      - "centos8-stream"
      - "ubi8"
      - "fedora33"
      - "fedora34"
      - "fedora35"
      - "rockylinux8"
      - "almalinux8"
      - "amazonlinux"
