---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Debian/Ubuntu | update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"
