---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: SmokeTests
      debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    # Repository
    - name: Test if Debian vimrc exists
      lineinfile:
        name: '/etc/vim/vimrc.local'
        line: 'syntax on'
        state: present
      check_mode: true
      register: vimrc
      failed_when: (vimrc is changed) or (vimrc is failed)
      when: ansible_os_family == "Debian"

    - name: verify vimrc filemode
      file:
        name: '/etc/vim/vimrc.local'
        owner: 'root'
        group: 'root'
        mode: "0744"
      register: mode_vimrc
      failed_when: (mode_vimrc is changed) or (mode_vimrc is failed)
      when: ansible_os_family == "Debian"

    - name: Test if RedHat vimrc exists
      lineinfile:
        name: '/etc/vimrc'
        line: 'syntax on'
        state: present
      check_mode: true
      register: vimrc
      failed_when: (vimrc is changed) or (vimrc is failed)
      when: ansible_os_family == "RedHat"

    - name: verify vimrc filemode
      file:
        name: '/etc/vimrc'
        owner: 'root'
        group: 'root'
        mode: "0744"
      register: mode_vimrc
      failed_when: (mode_vimrc is changed) or (mode_vimrc is failed)
      when: ansible_os_family == "RedHat"

    - name: Check if vim is installed
      ansible.builtin.package:
        name: "vim"
        state: present
      register: vim_installed
      failed_when: (vim_installed is changed) or (vim_installed is failed)
