---
# Ansible managed

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '43 22 22 * *'

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: mullholland/molecule-github-action@v0.1.1
        with:
          command: lint


  "default-29":
    needs:
      - linting
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos8, centos8-stream, ubi8, fedora33, fedora34, fedora35, rockylinux8, almalinux8, amazonlinux]  # yamllint disable-line rule:line-length

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: mullholland/molecule-github-action@v0.1.1
        with:
          namespace: "ghcr.io/mullholland"
          scenario: "default"
          ansible: "2.9"
          platform: "${{ matrix.platform }}"

  "default-210":
    needs:
      - linting
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos8, centos8-stream, ubi8, fedora33, fedora34, fedora35, rockylinux8, almalinux8, amazonlinux]  # yamllint disable-line rule:line-length

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: mullholland/molecule-github-action@v0.1.1
        with:
          namespace: "ghcr.io/mullholland"
          scenario: "default"
          ansible: "2.10"
          platform: "${{ matrix.platform }}"

  "default-211":
    needs:
      - linting
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos8, centos8-stream, ubi8, fedora33, fedora34, fedora35, rockylinux8, almalinux8, amazonlinux]  # yamllint disable-line rule:line-length

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: mullholland/molecule-github-action@v0.1.1
        with:
          namespace: "ghcr.io/mullholland"
          scenario: "default"
          ansible: "2.11"
          platform: "${{ matrix.platform }}"
